---
#region jenkins init folder check
- name: check if jenkins_init_folder exists
  stat:
    path: "{{ jenkins_init_folder }}"
  register: jenkins_init_folder_stat

- name: ensure jenkins_init_folder exists
  file:
    path: "{{ jenkins_init_folder }}"
    state: directory
    mode: 0644
  when: not jenkins_init_folder_stat.stat.exists
#endregion

#region jenkins init file check
- name: check if jenkins_init_file exists
  stat:
    path: "{{ jenkins_init_file }}"
  register: jenkins_init_file_stat

- name: ensure jenkins_init_file exists
  file:
    path: "{{ jenkins_init_file }}"
    state: touch
    mode: 0644
  when: not jenkins_init_file_stat.stat.exists
#endregion

#region configure jenkins init file
- name: populate jenkins_init_file with service tag
  copy:
    dest: "{{ jenkins_init_file }}"
    content: "[Service]"
  when: not jenkins_init_file_stat.stat.exists

- name: modify variables in init file
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^Environment="{{ item.option }}='
    regexp: '^Environment="{{ item.option }} '
    line: 'Environment="{{ item.option }}={{ item.value }}"'
    state: present
    mode: 0644
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init_prefix
#endregion

#region jenkins home check
- name: ensure jenkins_home {{ jenkins_home }} exists
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx
    follow: true
#endregion

#region jenkins restart
- name: Immediately restart Jenkins on init config changes.
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: true
  when: jenkins_init_prefix.changed
  tags: ['skip_ansible_lint']
#endregion

#region configure jenkins settings
- name: create custom init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: configure proxy config for jenkins
  template:
    src: proxy.xml
    dest: "{{ jenkins_home }}/proxy.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0664
  register: jenkins_proxy_config
  when:
    - jenkins_proxy_host | length > 0
    - jenkins_proxy_port | length > 0

- name: trigger handlers immediately in case jenkins was installed
  meta: flush_handlers

- name: immediately restart jenkins on http or user changes.
  service: name=jenkins state=restarted
  when: >
    (jenkins_users_config is defined and jenkins_users_config.changed)
    or (jenkins_http_config is defined and jenkins_http_config.changed)
    or (jenkins_home_config is defined and jenkins_home_config.changed)
    or (jenkins_proxy_config is defined and jenkins_proxy_config.changed)
  tags: ['skip_ansible_lint']
#endregion