---

#region install dependencies
- name: ensure dependencies are installed
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present
#endregion

#region install jenkins apt repo
- name: add jenkins apt repository key
  ansible.builtin.get_url:
    url: "{{ jenkins_repo_key_url }}"
    dest: /etc/apt/trusted.gpg.d/jenkins.asc
    mode: '0644'
    force: true

- name: add jenkins apt repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
  when: jenkins_repo_url | default(false)
  tags: ['skip_ansible_lint']
#endregion

#region download jenkins
- name: download specific jenkins version
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is defined

- name: check if we downloaded a specific version of jenkins
  stat:
    path: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  register: specific_version
  when: jenkins_version is defined
#endregion

#region install jenkins
- name: install our specific version of jenkins
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: present
  when: jenkins_version is defined and specific_version.stat.exists
  notify: configure default users

- name: ensure jenkins is installed
  apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"
  notify: configure default users
#endregion